name: Locust Performance Test

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  locust-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Locust tests
        run: |
          locust -f tests/activities_get_test.py --headless -u 10 -r 2 --run-time 30s --csv locust_result --logfile locust.log

      - name: Upload Locust log
        uses: actions/upload-artifact@v4
        with:
          name: locust-log
          path: locust.log

      - name: Upload Locust CSV results
        uses: actions/upload-artifact@v4
        with:
          name: locust-csv
          path: locust_result*.csv